In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\USERR\Documents\Arsenal Players python web scrapping project csv\Arsenal Players.csv")
df

,jersey_number,name,position,nationality,dob,height,foot,joined,contract,market_value
0,1,David Raya,Goalkeeper,Spain,15/09/1995 (30),"1,83m",right,04/07/2024,30/06/2028,€35.00m
1,13,Kepa Arrizabalaga,Goalkeeper,Spain,03/10/1994 (31),"1,88m",right,01/07/2025,30/06/2028,€7.00m
2,35,Tommy Setford,Goalkeeper,England,13/03/2006 (20),"1,85m",right,01/07/2025,30/06/2028,-
3,2,William Saliba,Centre-Back,France,24/03/2001 (25),"1,92m",right,25/07/2019,30/06/2030,€90.00m
4,6,Gabriel,Centre-Back,Brazil,19/12/1997 (28),"1,90m",left,01/09/2020,30/06/2029,€75.00m
5,5,Piero Hincapié,Centre-Back,Ecuador,09/01/2002 (24),"1,84m",left,01/09/2025,30/06/2026,€50.00m
6,3,Cristhian Mosquera,Centre-Back,Spain,27/06/2004 (21),"1,91m",right,24/07/2025,30/06/2030,€35.00m
7,33,Riccardo Calafiori,Left-Back,Italy,19/05/2002 (23),"1,88m",left,29/07/2024,30/06/2029,€50.00m
8,49,Myles Lewis-Skelly,Left-Back,England,26/09/2006 (19),"1,78m",left,01/07/2024,30/06/2030,€35.00m
9,12,Jurriën Timber,Right-Back,Netherlands,17/06/2001 (24),"1,79m",right,14/07/2023,30/06/2028,€70.00m
10,4,Ben White,Right-Back,England,08/10/1997 (28),"1,86m",right,30/07/2021,30/06/2028,€30.00m
11,36,Martín Zubimendi,Defensive Midfield,Spain,02/02/1999 (27),"1,81m",right,06/07/2025,30/06/2030,€80.00m
12,16,Christian Nørgaard,Defensive Midfield,Denmark,10/03/1994 (32),"1,87m",right,10/07/2025,30/06/2027,€7.00m
13,41,Declan Rice,Central Midfield,England,14/01/1999 (27),"1,88m",right,15/07/2023,30/06/2028,€120.00m
14,23,Mikel Merino,Central Midfield,Spain,22/06/1996 (29),"1,89m",left,27/08/2024,30/06/2028,€30.00m
15,8,Martin Ødegaard,Attacking Midfield,Norway,17/12/1998 (27),"1,78m",left,20/08/2021,30/06/2028,€65.00m
16,10,Eberechi Eze,Attacking Midfield,England,29/06/1998 (27),"1,78m",right,23/08/2025,30/06/2029,€60.00m
17,11,Gabriel Martinelli,Left Winger,Brazil,18/06/2001 (24),"1,78m",right,02/07/2019,30/06/2027,€45.00m
18,19,Leandro Trossard,Left Winger,Belgium,04/12/1994 (31),"1,72m",right,20/01/2023,30/06/2027,€20.00m
19,7,Bukayo Saka,Right Winger,England,05/09/2001 (24),"1,78m",left,01/07/2019,30/06/2030,€120.00m
20,20,Noni Madueke,Right Winger,England,10/03/2002 (24),"1,82m",left,18/07/2025,30/06/2030,€50.00m
21,56,Max Dowman,Right Winger,England,31/12/2009 (16),"1,83m",left,01/07/2025,-,€20.00m
22,14,Viktor Gyökeres,Centre-Forward,Sweden,04/06/1998 (27),"1,89m",right,26/07/2025,30/06/2030,€65.00m
23,29,Kai Havertz,Centre-Forward,Germany,11/06/1999 (26),"1,93m",left,01/07/2023,30/06/2028,€50.00m
24,9,Gabriel Jesus,Centre-Forward,Brazil,03/04/1997 (29),"1,75m",right,04/07/2022,30/06/2027,€20.00m

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   jersey_number  25 non-null     int64
 1   name           25 non-null     object
 2   position       25 non-null     object
 3   nationality    25 non-null     object
 4   dob            25 non-null     object
 5   height         25 non-null     object
 6   foot           25 non-null     object
 7   joined         25 non-null     object
 8   contract       25 non-null     object
 9   market_value   25 non-null     object
dtypes: int64(1), object(9)
memory usage: 2.1+ KB

In [4]:
df.head()

,jersey_number,name,position,nationality,dob,height,foot,joined,contract,market_value
0,1,David Raya,Goalkeeper,Spain,15/09/1995 (30),"1,83m",right,04/07/2024,30/06/2028,€35.00m
1,13,Kepa Arrizabalaga,Goalkeeper,Spain,03/10/1994 (31),"1,88m",right,01/07/2025,30/06/2028,€7.00m
2,35,Tommy Setford,Goalkeeper,England,13/03/2006 (20),"1,85m",right,01/07/2025,30/06/2028,-
3,2,William Saliba,Centre-Back,France,24/03/2001 (25),"1,92m",right,25/07/2019,30/06/2030,€90.00m
4,6,Gabriel,Centre-Back,Brazil,19/12/1997 (28),"1,90m",left,01/09/2020,30/06/2029,€75.00m

In [9]:
## df[] = df[] to save what we have cleaned as pandas doesnt automatically save, for players without market value python shows - hence we have to remove
## it, .str.strip) removes invisible white spaces from the beginig and end of a string, error = coerce converts what it cant make numeric into nan
df['market_value'] = df['market_value'].str.replace('€', '')
df['market_value'] = df['market_value'].str.replace('m', '')
df['market_value'] = df['market_value'].str.replace('-', '')
df['market_value'] = df['market_value'].str.strip()
df['market_value'] = pd.to_numeric(df['market_value'], errors = 'coerce')
df

,jersey_number,name,position,nationality,dob,height,foot,joined,contract,market_value
0,1,David Raya,Goalkeeper,Spain,15/09/1995 (30),"1,83m",right,04/07/2024,30/06/2028,35.0
1,13,Kepa Arrizabalaga,Goalkeeper,Spain,03/10/1994 (31),"1,88m",right,01/07/2025,30/06/2028,7.0
2,35,Tommy Setford,Goalkeeper,England,13/03/2006 (20),"1,85m",right,01/07/2025,30/06/2028,NaN
3,2,William Saliba,Centre-Back,France,24/03/2001 (25),"1,92m",right,25/07/2019,30/06/2030,90.0
4,6,Gabriel,Centre-Back,Brazil,19/12/1997 (28),"1,90m",left,01/09/2020,30/06/2029,75.0
5,5,Piero Hincapié,Centre-Back,Ecuador,09/01/2002 (24),"1,84m",left,01/09/2025,30/06/2026,50.0
6,3,Cristhian Mosquera,Centre-Back,Spain,27/06/2004 (21),"1,91m",right,24/07/2025,30/06/2030,35.0
7,33,Riccardo Calafiori,Left-Back,Italy,19/05/2002 (23),"1,88m",left,29/07/2024,30/06/2029,50.0
8,49,Myles Lewis-Skelly,Left-Back,England,26/09/2006 (19),"1,78m",left,01/07/2024,30/06/2030,35.0
9,12,Jurriën Timber,Right-Back,Netherlands,17/06/2001 (24),"1,79m",right,14/07/2023,30/06/2028,70.0
10,4,Ben White,Right-Back,England,08/10/1997 (28),"1,86m",right,30/07/2021,30/06/2028,30.0
11,36,Martín Zubimendi,Defensive Midfield,Spain,02/02/1999 (27),"1,81m",right,06/07/2025,30/06/2030,80.0
12,16,Christian Nørgaard,Defensive Midfield,Denmark,10/03/1994 (32),"1,87m",right,10/07/2025,30/06/2027,7.0
13,41,Declan Rice,Central Midfield,England,14/01/1999 (27),"1,88m",right,15/07/2023,30/06/2028,120.0
14,23,Mikel Merino,Central Midfield,Spain,22/06/1996 (29),"1,89m",left,27/08/2024,30/06/2028,30.0
15,8,Martin Ødegaard,Attacking Midfield,Norway,17/12/1998 (27),"1,78m",left,20/08/2021,30/06/2028,65.0
16,10,Eberechi Eze,Attacking Midfield,England,29/06/1998 (27),"1,78m",right,23/08/2025,30/06/2029,60.0
17,11,Gabriel Martinelli,Left Winger,Brazil,18/06/2001 (24),"1,78m",right,02/07/2019,30/06/2027,45.0
18,19,Leandro Trossard,Left Winger,Belgium,04/12/1994 (31),"1,72m",right,20/01/2023,30/06/2027,20.0
19,7,Bukayo Saka,Right Winger,England,05/09/2001 (24),"1,78m",left,01/07/2019,30/06/2030,120.0
20,20,Noni Madueke,Right Winger,England,10/03/2002 (24),"1,82m",left,18/07/2025,30/06/2030,50.0
21,56,Max Dowman,Right Winger,England,31/12/2009 (16),"1,83m",left,01/07/2025,-,20.0
22,14,Viktor Gyökeres,Centre-Forward,Sweden,04/06/1998 (27),"1,89m",right,26/07/2025,30/06/2030,65.0
23,29,Kai Havertz,Centre-Forward,Germany,11/06/1999 (26),"1,93m",left,01/07/2023,30/06/2028,50.0
24,9,Gabriel Jesus,Centre-Forward,Brazil,03/04/1997 (29),"1,75m",right,04/07/2022,30/06/2027,20.0

In [11]:
## to rename the column to signify millions
df = df.rename(columns = {'market_value' : 'market_value_millons'})
df

,jersey_number,name,position,nationality,dob,height,foot,joined,contract,market_value_millons
0,1,David Raya,Goalkeeper,Spain,15/09/1995 (30),"1,83m",right,04/07/2024,30/06/2028,35.0
1,13,Kepa Arrizabalaga,Goalkeeper,Spain,03/10/1994 (31),"1,88m",right,01/07/2025,30/06/2028,7.0
2,35,Tommy Setford,Goalkeeper,England,13/03/2006 (20),"1,85m",right,01/07/2025,30/06/2028,NaN
3,2,William Saliba,Centre-Back,France,24/03/2001 (25),"1,92m",right,25/07/2019,30/06/2030,90.0
4,6,Gabriel,Centre-Back,Brazil,19/12/1997 (28),"1,90m",left,01/09/2020,30/06/2029,75.0
5,5,Piero Hincapié,Centre-Back,Ecuador,09/01/2002 (24),"1,84m",left,01/09/2025,30/06/2026,50.0
6,3,Cristhian Mosquera,Centre-Back,Spain,27/06/2004 (21),"1,91m",right,24/07/2025,30/06/2030,35.0
7,33,Riccardo Calafiori,Left-Back,Italy,19/05/2002 (23),"1,88m",left,29/07/2024,30/06/2029,50.0
8,49,Myles Lewis-Skelly,Left-Back,England,26/09/2006 (19),"1,78m",left,01/07/2024,30/06/2030,35.0
9,12,Jurriën Timber,Right-Back,Netherlands,17/06/2001 (24),"1,79m",right,14/07/2023,30/06/2028,70.0
10,4,Ben White,Right-Back,England,08/10/1997 (28),"1,86m",right,30/07/2021,30/06/2028,30.0
11,36,Martín Zubimendi,Defensive Midfield,Spain,02/02/1999 (27),"1,81m",right,06/07/2025,30/06/2030,80.0
12,16,Christian Nørgaard,Defensive Midfield,Denmark,10/03/1994 (32),"1,87m",right,10/07/2025,30/06/2027,7.0
13,41,Declan Rice,Central Midfield,England,14/01/1999 (27),"1,88m",right,15/07/2023,30/06/2028,120.0
14,23,Mikel Merino,Central Midfield,Spain,22/06/1996 (29),"1,89m",left,27/08/2024,30/06/2028,30.0
15,8,Martin Ødegaard,Attacking Midfield,Norway,17/12/1998 (27),"1,78m",left,20/08/2021,30/06/2028,65.0
16,10,Eberechi Eze,Attacking Midfield,England,29/06/1998 (27),"1,78m",right,23/08/2025,30/06/2029,60.0
17,11,Gabriel Martinelli,Left Winger,Brazil,18/06/2001 (24),"1,78m",right,02/07/2019,30/06/2027,45.0
18,19,Leandro Trossard,Left Winger,Belgium,04/12/1994 (31),"1,72m",right,20/01/2023,30/06/2027,20.0
19,7,Bukayo Saka,Right Winger,England,05/09/2001 (24),"1,78m",left,01/07/2019,30/06/2030,120.0
20,20,Noni Madueke,Right Winger,England,10/03/2002 (24),"1,82m",left,18/07/2025,30/06/2030,50.0
21,56,Max Dowman,Right Winger,England,31/12/2009 (16),"1,83m",left,01/07/2025,-,20.0
22,14,Viktor Gyökeres,Centre-Forward,Sweden,04/06/1998 (27),"1,89m",right,26/07/2025,30/06/2030,65.0
23,29,Kai Havertz,Centre-Forward,Germany,11/06/1999 (26),"1,93m",left,01/07/2023,30/06/2028,50.0
24,9,Gabriel Jesus,Centre-Forward,Brazil,03/04/1997 (29),"1,75m",right,04/07/2022,30/06/2027,20.0

In [12]:
## to remove , amd m from height
df['height'] = df['height'].str.replace('m', '')
df['height'] = df['height'].str.replace(',', '')
df

,jersey_number,name,position,nationality,dob,height,foot,joined,contract,market_value_millons
0,1,David Raya,Goalkeeper,Spain,15/09/1995 (30),183,right,04/07/2024,30/06/2028,35.0
1,13,Kepa Arrizabalaga,Goalkeeper,Spain,03/10/1994 (31),188,right,01/07/2025,30/06/2028,7.0
2,35,Tommy Setford,Goalkeeper,England,13/03/2006 (20),185,right,01/07/2025,30/06/2028,NaN
3,2,William Saliba,Centre-Back,France,24/03/2001 (25),192,right,25/07/2019,30/06/2030,90.0
4,6,Gabriel,Centre-Back,Brazil,19/12/1997 (28),190,left,01/09/2020,30/06/2029,75.0
5,5,Piero Hincapié,Centre-Back,Ecuador,09/01/2002 (24),184,left,01/09/2025,30/06/2026,50.0
6,3,Cristhian Mosquera,Centre-Back,Spain,27/06/2004 (21),191,right,24/07/2025,30/06/2030,35.0
7,33,Riccardo Calafiori,Left-Back,Italy,19/05/2002 (23),188,left,29/07/2024,30/06/2029,50.0
8,49,Myles Lewis-Skelly,Left-Back,England,26/09/2006 (19),178,left,01/07/2024,30/06/2030,35.0
9,12,Jurriën Timber,Right-Back,Netherlands,17/06/2001 (24),179,right,14/07/2023,30/06/2028,70.0
10,4,Ben White,Right-Back,England,08/10/1997 (28),186,right,30/07/2021,30/06/2028,30.0
11,36,Martín Zubimendi,Defensive Midfield,Spain,02/02/1999 (27),181,right,06/07/2025,30/06/2030,80.0
12,16,Christian Nørgaard,Defensive Midfield,Denmark,10/03/1994 (32),187,right,10/07/2025,30/06/2027,7.0
13,41,Declan Rice,Central Midfield,England,14/01/1999 (27),188,right,15/07/2023,30/06/2028,120.0
14,23,Mikel Merino,Central Midfield,Spain,22/06/1996 (29),189,left,27/08/2024,30/06/2028,30.0
15,8,Martin Ødegaard,Attacking Midfield,Norway,17/12/1998 (27),178,left,20/08/2021,30/06/2028,65.0
16,10,Eberechi Eze,Attacking Midfield,England,29/06/1998 (27),178,right,23/08/2025,30/06/2029,60.0
17,11,Gabriel Martinelli,Left Winger,Brazil,18/06/2001 (24),178,right,02/07/2019,30/06/2027,45.0
18,19,Leandro Trossard,Left Winger,Belgium,04/12/1994 (31),172,right,20/01/2023,30/06/2027,20.0
19,7,Bukayo Saka,Right Winger,England,05/09/2001 (24),178,left,01/07/2019,30/06/2030,120.0
20,20,Noni Madueke,Right Winger,England,10/03/2002 (24),182,left,18/07/2025,30/06/2030,50.0
21,56,Max Dowman,Right Winger,England,31/12/2009 (16),183,left,01/07/2025,-,20.0
22,14,Viktor Gyökeres,Centre-Forward,Sweden,04/06/1998 (27),189,right,26/07/2025,30/06/2030,65.0
23,29,Kai Havertz,Centre-Forward,Germany,11/06/1999 (26),193,left,01/07/2023,30/06/2028,50.0
24,9,Gabriel Jesus,Centre-Forward,Brazil,03/04/1997 (29),175,right,04/07/2022,30/06/2027,20.0

In [14]:
print(df['height'].head())

0    183
1    188
2    185
3    192
4    190
Name: height, dtype: object

In [15]:
## lets rename the column
df = df.rename(columns = {'height' : 'height_cm'})
df

,jersey_number,name,position,nationality,dob,height_cm,foot,joined,contract,market_value_millons
0,1,David Raya,Goalkeeper,Spain,15/09/1995 (30),183,right,04/07/2024,30/06/2028,35.0
1,13,Kepa Arrizabalaga,Goalkeeper,Spain,03/10/1994 (31),188,right,01/07/2025,30/06/2028,7.0
2,35,Tommy Setford,Goalkeeper,England,13/03/2006 (20),185,right,01/07/2025,30/06/2028,NaN
3,2,William Saliba,Centre-Back,France,24/03/2001 (25),192,right,25/07/2019,30/06/2030,90.0
4,6,Gabriel,Centre-Back,Brazil,19/12/1997 (28),190,left,01/09/2020,30/06/2029,75.0
5,5,Piero Hincapié,Centre-Back,Ecuador,09/01/2002 (24),184,left,01/09/2025,30/06/2026,50.0
6,3,Cristhian Mosquera,Centre-Back,Spain,27/06/2004 (21),191,right,24/07/2025,30/06/2030,35.0
7,33,Riccardo Calafiori,Left-Back,Italy,19/05/2002 (23),188,left,29/07/2024,30/06/2029,50.0
8,49,Myles Lewis-Skelly,Left-Back,England,26/09/2006 (19),178,left,01/07/2024,30/06/2030,35.0
9,12,Jurriën Timber,Right-Back,Netherlands,17/06/2001 (24),179,right,14/07/2023,30/06/2028,70.0
10,4,Ben White,Right-Back,England,08/10/1997 (28),186,right,30/07/2021,30/06/2028,30.0
11,36,Martín Zubimendi,Defensive Midfield,Spain,02/02/1999 (27),181,right,06/07/2025,30/06/2030,80.0
12,16,Christian Nørgaard,Defensive Midfield,Denmark,10/03/1994 (32),187,right,10/07/2025,30/06/2027,7.0
13,41,Declan Rice,Central Midfield,England,14/01/1999 (27),188,right,15/07/2023,30/06/2028,120.0
14,23,Mikel Merino,Central Midfield,Spain,22/06/1996 (29),189,left,27/08/2024,30/06/2028,30.0
15,8,Martin Ødegaard,Attacking Midfield,Norway,17/12/1998 (27),178,left,20/08/2021,30/06/2028,65.0
16,10,Eberechi Eze,Attacking Midfield,England,29/06/1998 (27),178,right,23/08/2025,30/06/2029,60.0
17,11,Gabriel Martinelli,Left Winger,Brazil,18/06/2001 (24),178,right,02/07/2019,30/06/2027,45.0
18,19,Leandro Trossard,Left Winger,Belgium,04/12/1994 (31),172,right,20/01/2023,30/06/2027,20.0
19,7,Bukayo Saka,Right Winger,England,05/09/2001 (24),178,left,01/07/2019,30/06/2030,120.0
20,20,Noni Madueke,Right Winger,England,10/03/2002 (24),182,left,18/07/2025,30/06/2030,50.0
21,56,Max Dowman,Right Winger,England,31/12/2009 (16),183,left,01/07/2025,-,20.0
22,14,Viktor Gyökeres,Centre-Forward,Sweden,04/06/1998 (27),189,right,26/07/2025,30/06/2030,65.0
23,29,Kai Havertz,Centre-Forward,Germany,11/06/1999 (26),193,left,01/07/2023,30/06/2028,50.0
24,9,Gabriel Jesus,Centre-Forward,Brazil,03/04/1997 (29),175,right,04/07/2022,30/06/2027,20.0

In [16]:
## now to extract the age from the dob, find an opening bracket\( then (d+) find one or more digits, then \) find a closing bracket
df['age'] = df['dob'].str.extract(r'\((\d+)\)')
df['age'].head()

0    30
1    31
2    20
3    25
4    28
Name: age, dtype: object

In [17]:
df

,jersey_number,name,position,nationality,dob,height_cm,foot,joined,contract,market_value_millons,age
0,1,David Raya,Goalkeeper,Spain,15/09/1995 (30),183,right,04/07/2024,30/06/2028,35.0,30
1,13,Kepa Arrizabalaga,Goalkeeper,Spain,03/10/1994 (31),188,right,01/07/2025,30/06/2028,7.0,31
2,35,Tommy Setford,Goalkeeper,England,13/03/2006 (20),185,right,01/07/2025,30/06/2028,NaN,20
3,2,William Saliba,Centre-Back,France,24/03/2001 (25),192,right,25/07/2019,30/06/2030,90.0,25
4,6,Gabriel,Centre-Back,Brazil,19/12/1997 (28),190,left,01/09/2020,30/06/2029,75.0,28
5,5,Piero Hincapié,Centre-Back,Ecuador,09/01/2002 (24),184,left,01/09/2025,30/06/2026,50.0,24
6,3,Cristhian Mosquera,Centre-Back,Spain,27/06/2004 (21),191,right,24/07/2025,30/06/2030,35.0,21
7,33,Riccardo Calafiori,Left-Back,Italy,19/05/2002 (23),188,left,29/07/2024,30/06/2029,50.0,23
8,49,Myles Lewis-Skelly,Left-Back,England,26/09/2006 (19),178,left,01/07/2024,30/06/2030,35.0,19
9,12,Jurriën Timber,Right-Back,Netherlands,17/06/2001 (24),179,right,14/07/2023,30/06/2028,70.0,24
10,4,Ben White,Right-Back,England,08/10/1997 (28),186,right,30/07/2021,30/06/2028,30.0,28
11,36,Martín Zubimendi,Defensive Midfield,Spain,02/02/1999 (27),181,right,06/07/2025,30/06/2030,80.0,27
12,16,Christian Nørgaard,Defensive Midfield,Denmark,10/03/1994 (32),187,right,10/07/2025,30/06/2027,7.0,32
13,41,Declan Rice,Central Midfield,England,14/01/1999 (27),188,right,15/07/2023,30/06/2028,120.0,27
14,23,Mikel Merino,Central Midfield,Spain,22/06/1996 (29),189,left,27/08/2024,30/06/2028,30.0,29
15,8,Martin Ødegaard,Attacking Midfield,Norway,17/12/1998 (27),178,left,20/08/2021,30/06/2028,65.0,27
16,10,Eberechi Eze,Attacking Midfield,England,29/06/1998 (27),178,right,23/08/2025,30/06/2029,60.0,27
17,11,Gabriel Martinelli,Left Winger,Brazil,18/06/2001 (24),178,right,02/07/2019,30/06/2027,45.0,24
18,19,Leandro Trossard,Left Winger,Belgium,04/12/1994 (31),172,right,20/01/2023,30/06/2027,20.0,31
19,7,Bukayo Saka,Right Winger,England,05/09/2001 (24),178,left,01/07/2019,30/06/2030,120.0,24
20,20,Noni Madueke,Right Winger,England,10/03/2002 (24),182,left,18/07/2025,30/06/2030,50.0,24
21,56,Max Dowman,Right Winger,England,31/12/2009 (16),183,left,01/07/2025,-,20.0,16
22,14,Viktor Gyökeres,Centre-Forward,Sweden,04/06/1998 (27),189,right,26/07/2025,30/06/2030,65.0,27
23,29,Kai Havertz,Centre-Forward,Germany,11/06/1999 (26),193,left,01/07/2023,30/06/2028,50.0,26
24,9,Gabriel Jesus,Centre-Forward,Brazil,03/04/1997 (29),175,right,04/07/2022,30/06/2027,20.0,29

In [18]:
print(df['dob'].head())

0    15/09/1995 (30)
1    03/10/1994 (31)
2    13/03/2006 (20)
3    24/03/2001 (25)
4    19/12/1997 (28)
Name: dob, dtype: object

In [19]:
## to convert age to integer
df['age'] = df['age'].astype(int)

In [20]:
## to emove the extracted age from dob column, \s* remove white spaces befoe the bracket, \( find open bracket, .* match anything inside the bracket
## \) find closing bracket regex = true tell python that ths a regular expression not a literal string so python isnt looking for \s*\(.*\)
df['dob'] = df['dob'].str.replace(r'\s*\(.*\)', '', regex=True).str.strip()

In [21]:
## to convert dob to proper date
df['dob'] = pd.to_datetime(df['dob'], format='%d/%m/%Y')
print(df['dob'].head())

0   1995-09-15
1   1994-10-03
2   2006-03-13
3   2001-03-24
4   1997-12-19
Name: dob, dtype: datetime64[ns]

In [23]:
df['joined'] = pd.to_datetime(df['joined'], format='%d/%m/%Y')

In [24]:
df['contract'] = pd.to_datetime(df['contract'], format='%d/%m/%Y')
df

ValueError: time data "-" doesn't match format "%d/%m/%Y", at position 21. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [25]:
print(df['contract'].unique())

['30/06/2028' '30/06/2030' '30/06/2029' '30/06/2026' '30/06/2027' '-']

In [27]:
df['contract'] = pd.to_datetime(df['contract'], format='%d/%m/%Y', errors = 'coerce')
df

,jersey_number,name,position,nationality,dob,height_cm,foot,joined,contract,market_value_millons,age
0,1,David Raya,Goalkeeper,Spain,1995-09-15,183,right,2024-07-04,2028-06-30,35.0,30
1,13,Kepa Arrizabalaga,Goalkeeper,Spain,1994-10-03,188,right,2025-07-01,2028-06-30,7.0,31
2,35,Tommy Setford,Goalkeeper,England,2006-03-13,185,right,2025-07-01,2028-06-30,NaN,20
3,2,William Saliba,Centre-Back,France,2001-03-24,192,right,2019-07-25,2030-06-30,90.0,25
4,6,Gabriel,Centre-Back,Brazil,1997-12-19,190,left,2020-09-01,2029-06-30,75.0,28
5,5,Piero Hincapié,Centre-Back,Ecuador,2002-01-09,184,left,2025-09-01,2026-06-30,50.0,24
6,3,Cristhian Mosquera,Centre-Back,Spain,2004-06-27,191,right,2025-07-24,2030-06-30,35.0,21
7,33,Riccardo Calafiori,Left-Back,Italy,2002-05-19,188,left,2024-07-29,2029-06-30,50.0,23
8,49,Myles Lewis-Skelly,Left-Back,England,2006-09-26,178,left,2024-07-01,2030-06-30,35.0,19
9,12,Jurriën Timber,Right-Back,Netherlands,2001-06-17,179,right,2023-07-14,2028-06-30,70.0,24
10,4,Ben White,Right-Back,England,1997-10-08,186,right,2021-07-30,2028-06-30,30.0,28
11,36,Martín Zubimendi,Defensive Midfield,Spain,1999-02-02,181,right,2025-07-06,2030-06-30,80.0,27
12,16,Christian Nørgaard,Defensive Midfield,Denmark,1994-03-10,187,right,2025-07-10,2027-06-30,7.0,32
13,41,Declan Rice,Central Midfield,England,1999-01-14,188,right,2023-07-15,2028-06-30,120.0,27
14,23,Mikel Merino,Central Midfield,Spain,1996-06-22,189,left,2024-08-27,2028-06-30,30.0,29
15,8,Martin Ødegaard,Attacking Midfield,Norway,1998-12-17,178,left,2021-08-20,2028-06-30,65.0,27
16,10,Eberechi Eze,Attacking Midfield,England,1998-06-29,178,right,2025-08-23,2029-06-30,60.0,27
17,11,Gabriel Martinelli,Left Winger,Brazil,2001-06-18,178,right,2019-07-02,2027-06-30,45.0,24
18,19,Leandro Trossard,Left Winger,Belgium,1994-12-04,172,right,2023-01-20,2027-06-30,20.0,31
19,7,Bukayo Saka,Right Winger,England,2001-09-05,178,left,2019-07-01,2030-06-30,120.0,24
20,20,Noni Madueke,Right Winger,England,2002-03-10,182,left,2025-07-18,2030-06-30,50.0,24
21,56,Max Dowman,Right Winger,England,2009-12-31,183,left,2025-07-01,NaT,20.0,16
22,14,Viktor Gyökeres,Centre-Forward,Sweden,1998-06-04,189,right,2025-07-26,2030-06-30,65.0,27
23,29,Kai Havertz,Centre-Forward,Germany,1999-06-11,193,left,2023-07-01,2028-06-30,50.0,26
24,9,Gabriel Jesus,Centre-Forward,Brazil,1997-04-03,175,right,2022-07-04,2027-06-30,20.0,29

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   jersey_number         25 non-null     int64
 1   name                  25 non-null     object
 2   position              25 non-null     object
 3   nationality           25 non-null     object
 4   dob                   25 non-null     datetime64[ns]
 5   height_cm             25 non-null     object
 6   foot                  25 non-null     object
 7   joined                25 non-null     datetime64[ns]
 8   contract              24 non-null     datetime64[ns]
 9   market_value_millons  24 non-null     float64
 10  age                   25 non-null     int32
dtypes: datetime64[ns](3), float64(1), int32(1), int64(1), object(5)
memory usage: 2.2+ KB

In [29]:
df['height_cm'] = pd.to_numeric(df['height_cm'], errors='coerce').astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   jersey_number         25 non-null     int64
 1   name                  25 non-null     object
 2   position              25 non-null     object
 3   nationality           25 non-null     object
 4   dob                   25 non-null     datetime64[ns]
 5   height_cm             25 non-null     int32
 6   foot                  25 non-null     object
 7   joined                25 non-null     datetime64[ns]
 8   contract              24 non-null     datetime64[ns]
 9   market_value_millons  24 non-null     float64
 10  age                   25 non-null     int32
dtypes: datetime64[ns](3), float64(1), int32(2), int64(1), object(4)
memory usage: 2.1+ KB

In [30]:
df.to_csv("arsenals_player_clean.csv", index = False)

In [32]:
import os
os.path.exists("arsenals_player_clean.csv")

True